export interface CartEntity {
    cart_id?: number;        // Cart ID (optional, as it may be generated by the database)
    customer_id: number;     // Customer ID (required)
    book_id: number;         // Book ID (required)
    created_at?: Date;       // Created At timestamp (optional)
    updated_at?: Date;       // Updated At timestamp (optional)
  }
  